title: Jessica Eldredge
email: jessica@eldredge.io
description: >
Web designer/developer, sketchnoter, word nerd
baseurl: "" 
url: "http://jessica-eldredge.com" 
twitter_username: jessabean
github_username:  jessabean

# Build settings
markdown: redcarpet
highlighter: null
future: true
permalink: pretty
paginate: 0
paginate_path: 'page:num'
include: ['.htaccess', 'favicon.ico', 'apple-touch-icon-precomposed.png']
exclude: ["node_modules", "gulpfile.js", "package.json"]
